# Atividade prática com datasets de energia (Python e Pandas)

Ciência da Computação | Soluções em Energias Renováveis e Sustentáveis

Grupo:

* Andre Santos de Azevedo (RM572236)
* Guilherme Henrique de Almeida (RM568708)

As amostras *_SAMPLE.csv foram geradas na Etapa A de cada dataset (seleção de colunas, verificação de valores ausentes e amostragem aleatória) e devem estar na mesma pasta do notebook.

In [1]:
import pandas as pd

# Dataset 1: Appliances Energy Prediction (UCI)

Situação: uma empresa de eficiência energética está analisando o comportamento de uma residência de baixo consumo. A equipe deseja identificar períodos de consumo elevado dos eletrodomésticos e observar quais condições de temperatura e umidade estavam presentes nesses momentos.

Amostra: 10% dos registros (energydata_SAMPLE.csv).

untitled.svg

In [2]:
# Carregar a amostra (o arquivo energydata_SAMPLE.csv deve estar na mesma pasta do notebook)
df1 = pd.read_csv('energydata_SAMPLE.csv')

In [3]:
# Visualizar
df1.head()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
0,40,0,20.890000,35.400000,17.760000,39.163333,20.290000,36.900000
1,90,10,21.890000,53.100000,21.290000,45.360000,21.633333,49.226667
2,50,0,21.390000,35.500000,17.633333,40.530000,21.666667,35.200000
3,50,0,21.390000,41.033333,23.890000,34.840000,22.033333,36.933333
4,70,0,19.963333,35.126667,16.463333,40.126667,20.000000,36.400000


In [4]:
df1.shape

(1974, 8)

In [5]:
print(f'Total de registros: {df1.shape[0]}')
print(f'Total de colunas: {df1.shape[1]}')

Total de registros: 1974
Total de colunas: 8


In [6]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1974 entries, 0 to 1973
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Appliances  1974 non-null   int64  
 1   lights      1974 non-null   int64  
 2   T1          1974 non-null   float64
 3   RH_1        1974 non-null   float64
 4   T2          1974 non-null   float64
 5   RH_2        1974 non-null   float64
 6   T3          1974 non-null   float64
 7   RH_3        1974 non-null   float64
dtypes: float64(6), int64(2)
memory usage: 123.5 KB


In [7]:
df1.describe()

,Appliances,lights,T1,RH_1,T2,RH_2,T3,RH_3
count,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000,1974.000000
mean,93.044580,3.839919,21.664702,40.219194,20.293635,40.411386,22.231615,39.209733
std,93.826149,7.937076,1.574883,3.971923,2.126958,4.037685,1.957275,3.288818
min,20.000000,0.000000,16.790000,27.733333,16.100000,24.063333,17.200000,30.133333
25%,50.000000,0.000000,20.700000,37.205833,18.790000,37.760000,20.700000,36.900000
50%,60.000000,0.000000,21.600000,39.590000,20.000000,40.433333,22.100000,38.433333
75%,100.000000,0.000000,22.600000,42.991667,21.500000,43.228333,23.290000,41.741250
max,770.000000,50.000000,26.260000,57.496667,28.917500,56.026667,29.198571,49.226667


In [8]:
df1.columns

Index(['Appliances', 'lights', 'T1', 'RH_1', 'T2', 'RH_2', 'T3', 'RH_3'], dtype='object')

In [9]:
# 2.	Renomeie Appliances para Consumo_Eletrodomesticos e simplifique o nome de pelo menos três atributos ambientais.
df1.rename(columns={'Appliances':'Consumo_Eletrodomesticos',
                    'T1': 'Temperatura_1',
                    'T2': 'Temperatura_2',
                    'T3': 'Temperatura_3'
                    }, inplace=True)

In [10]:
df1.columns

Index(['Consumo_Eletrodomesticos', 'lights', 'Temperatura_1', 'RH_1',
       'Temperatura_2', 'RH_2', 'Temperatura_3', 'RH_3'],
      dtype='object')

In [11]:
df1.head()

,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatura_3,RH_3
0,40,0,20.890000,35.400000,17.760000,39.163333,20.290000,36.900000
1,90,10,21.890000,53.100000,21.290000,45.360000,21.633333,49.226667
2,50,0,21.390000,35.500000,17.633333,40.530000,21.666667,35.200000
3,50,0,21.390000,41.033333,23.890000,34.840000,22.033333,36.933333
4,70,0,19.963333,35.126667,16.463333,40.126667,20.000000,36.400000


In [12]:
# 3.	Determine o maior consumo de eletrodomésticos registrado na amostra.
maximo = df1['Consumo_Eletrodomesticos'].max()
print(f'Maior consumo de eletrodomésticos registrado na amostra: {maximo} Wh')

Maior consumo de eletrodomésticos registrado na amostra: 770 Wh


In [13]:
# 4.	Calcule um limiar correspondente a 70% do valor máximo e crie um DataFrame
#     contendo somente os registros acima desse limite.
limiar_70 = 0.70 * maximo
print(f'Limiar (70% do máximo): {limiar_70} Wh')

df1_alto = df1[df1['Consumo_Eletrodomesticos'] > limiar_70]
df1_alto.head()

Limiar (70% do máximo): 539.0 Wh


,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatura_3,RH_3
352,620,0,24.390000,44.333333,25.370000,37.736000,26.730000,38.863333
427,650,0,20.890000,36.700000,18.290000,39.663333,21.200000,36.000000
453,560,30,21.356667,36.090000,19.566667,37.163333,21.633333,35.030000
616,570,10,24.890000,32.666667,23.560000,31.140000,23.600000,30.823333
696,590,30,19.856667,47.663333,18.700000,34.100000,18.426667,37.833333


In [14]:
# 5.	Conte os registros selecionados e calcule qual percentual da amostra eles representam.
qtd_alto = len(df1_alto)
percentual_alto = qtd_alto / len(df1) * 100
print(f'Registros com consumo acima do limiar: {qtd_alto}')
print(f'Percentual da amostra: {percentual_alto:.2f}%')

Registros com consumo acima do limiar: 22
Percentual da amostra: 1.11%


In [15]:
# 6.	Calcule a temperatura média de T1 e crie outro DataFrame contendo simultaneamente
#     consumo acima de 70% do máximo e temperatura acima da média.
media_T1 = df1['Temperatura_1'].mean()
print(f'Temperatura média de T1: {media_T1:.2f} °C')

df1_alto_temp = df1[(df1['Consumo_Eletrodomesticos'] > limiar_70) &
                    (df1['Temperatura_1'] > media_T1)]
df1_alto_temp.head()

Temperatura média de T1: 21.66 °C


,Consumo_Eletrodomesticos,lights,Temperatura_1,RH_1,Temperatura_2,RH_2,Temperatura_3,RH_3
352,620,0,24.390000,44.333333,25.370000,37.736000,26.73,38.863333
616,570,10,24.890000,32.666667,23.560000,31.140000,23.60,30.823333
916,750,30,22.430000,43.000000,21.926667,40.133333,21.23,42.596667
993,690,10,22.533333,45.026667,22.066667,39.790000,22.39,41.930000
1182,600,20,24.890000,48.133333,28.917500,37.947500,27.10,42.440000


In [16]:
# 7.	Compare os dois DataFrames.
qtd_alto_temp = len(df1_alto_temp)
percentual_alto_temp = qtd_alto_temp / len(df1) * 100
print(f'Somente consumo > 70% do máximo: {qtd_alto} registros ({percentual_alto:.2f}%)')
print(f'Consumo alto e T1 acima da média: {qtd_alto_temp} registros ({percentual_alto_temp:.2f}%)')
print(f'Diferença: {qtd_alto - qtd_alto_temp} registros')

Somente consumo > 70% do máximo: 22 registros (1.11%)
Consumo alto e T1 acima da média: 8 registros (0.41%)
Diferença: 14 registros


Análise: o filtro de consumo acima de 70% do máximo (539 Wh) seleciona 22 registros, cerca de 1,1% da amostra, ou seja, picos de consumo são raros nessa residência. Exigindo também T1 acima da média (21,66 °C) sobram 8 registros (0,41%). Como as condições são combinadas com &, o segundo DataFrame é um subconjunto do primeiro. A maior parte dos picos ocorreu com temperatura igual ou abaixo da média, e o segundo critério serve para localizar só os casos de consumo alto em ambiente mais quente.

# Dataset 2: Steel Industry Energy Consumption (UCI)

Situação: a equipe de gestão de energia de uma indústria siderúrgica deseja localizar situações de consumo elevado e verificar se esses períodos coincidem com carga elevada ou com valores menos favoráveis de fator de potência.

Amostra: 20% dos registros (steel_SAMPLE.csv), com Usage_kWh, potências reativas, fatores de potência, WeekStatus, Day_of_week e Load_Type.

In [17]:
# 1.	Carregue a amostra e renomeie Usage_kWh para Consumo_kWh,
#   	simplificando também os nomes dos atributos de fator de potência.
df2 = pd.read_csv('steel_SAMPLE.csv')
df2.rename(columns={'Usage_kWh': 'Consumo_kWh',
                    'Lagging_Current_Reactive.Power_kVarh': 'Pot_Reativa_Atraso_kVarh',
                    'Leading_Current_Reactive_Power_kVarh': 'Pot_Reativa_Avanco_kVarh',
                    'Lagging_Current_Power_Factor': 'FP_Atraso',
                    'Leading_Current_Power_Factor': 'FP_Avanco'}, inplace=True)
df2.columns

Index(['Consumo_kWh', 'Pot_Reativa_Atraso_kVarh', 'Pot_Reativa_Avanco_kVarh',
       'FP_Atraso', 'FP_Avanco', 'WeekStatus', 'Day_of_week', 'Load_Type'],
      dtype='object')

In [18]:
# 2.	Inspeção inicial
df2.head()

,Consumo_kWh,Pot_Reativa_Atraso_kVarh,Pot_Reativa_Avanco_kVarh,FP_Atraso,FP_Avanco,WeekStatus,Day_of_week,Load_Type
0,2.88,3.82,0.0,60.20,100.00,Weekend,Sunday,Light_Load
1,60.77,48.02,0.0,78.46,100.00,Weekday,Thursday,Maximum_Load
2,120.42,59.65,0.0,89.61,100.00,Weekday,Friday,Maximum_Load
3,3.13,0.00,16.6,100.00,18.53,Weekend,Saturday,Light_Load
4,58.86,20.99,0.0,94.19,100.00,Weekday,Friday,Medium_Load


In [19]:
print(f'Total de registros: {df2.shape[0]}')
print(f'Total de colunas: {df2.shape[1]}')

Total de registros: 7008
Total de colunas: 8


In [20]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7008 entries, 0 to 7007
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Consumo_kWh               7008 non-null   float64
 1   Pot_Reativa_Atraso_kVarh  7008 non-null   float64
 2   Pot_Reativa_Avanco_kVarh  7008 non-null   float64
 3   FP_Atraso                 7008 non-null   float64
 4   FP_Avanco                 7008 non-null   float64
 5   WeekStatus                7008 non-null   object 
 6   Day_of_week               7008 non-null   object 
 7   Load_Type                 7008 non-null   object 
dtypes: float64(5), object(3)
memory usage: 438.1+ KB


In [21]:
df2.describe()

,Consumo_kWh,Pot_Reativa_Atraso_kVarh,Pot_Reativa_Avanco_kVarh,FP_Atraso,FP_Avanco
count,7008.000000,7008.000000,7008.000000,7008.000000,7008.000000
mean,27.790164,13.206839,3.803711,80.672277,84.491448
std,33.717719,16.444246,7.356412,18.869855,30.314798
min,2.450000,0.000000,0.000000,37.870000,12.710000
25%,3.200000,2.380000,0.000000,63.602500,99.710000
50%,4.570000,5.040000,0.000000,87.990000,100.000000
75%,52.107500,22.977500,1.857500,98.842500,100.000000
max,153.140000,87.700000,27.650000,100.000000,100.000000


In [22]:
# 3.	Determine o maior consumo registrado e calcule um limiar de 75% do consumo máximo.
maximo2 = df2['Consumo_kWh'].max()
limiar2_75 = 0.75 * maximo2
print(f'Maior consumo registrado: {maximo2} kWh')
print(f'Limiar (75% do máximo): {limiar2_75:.2f} kWh')

Maior consumo registrado: 153.14 kWh
Limiar (75% do máximo): 114.85 kWh


In [23]:
# 4.	Crie um DataFrame com os registros acima do limiar e calcule quantidade e percentual.
df2_alto = df2[df2['Consumo_kWh'] > limiar2_75]
qtd2_alto = len(df2_alto)
pct2_alto = qtd2_alto / len(df2) * 100
print(f'Registros acima do limiar: {qtd2_alto}')
print(f'Percentual da amostra: {pct2_alto:.2f}%')
df2_alto.head()

Registros acima do limiar: 129
Percentual da amostra: 1.84%


,Consumo_kWh,Pot_Reativa_Atraso_kVarh,Pot_Reativa_Avanco_kVarh,FP_Atraso,FP_Avanco,WeekStatus,Day_of_week,Load_Type
2,120.42,59.65,0.0,89.61,100.0,Weekday,Friday,Maximum_Load
62,118.22,54.04,0.0,90.95,100.0,Weekday,Thursday,Medium_Load
100,129.13,46.58,0.0,94.07,100.0,Weekday,Monday,Medium_Load
108,117.07,46.44,0.0,92.95,100.0,Weekday,Monday,Medium_Load
159,139.57,58.90,0.0,92.13,100.0,Weekday,Thursday,Maximum_Load


In [24]:
# 5.	Verifique quantos registros desse DataFrame pertencem à categoria Maximum Load.
print(df2_alto['Load_Type'].value_counts())
qtd2_max_load = len(df2_alto[df2_alto['Load_Type'] == 'Maximum_Load'])
print(f'\nRegistros de alto consumo na categoria Maximum_Load: {qtd2_max_load}')

Load_Type
Maximum_Load    62
Medium_Load     58
Light_Load       9
Name: count, dtype: int64

Registros de alto consumo na categoria Maximum_Load: 62


In [25]:
# 6.	Observe os valores de um atributo de fator de potência para definir um limite coerente.
df2['FP_Atraso'].describe()

count    7008.000000
mean       80.672277
std        18.869855
min        37.870000
25%        63.602500
50%        87.990000
75%        98.842500
max       100.000000
Name: FP_Atraso, dtype: float64

In [26]:
# 7.	DataFrame com consumo elevado E fator de potência abaixo do limite escolhido.
#   	Limite escolhido: FP_Atraso < 90 (abaixo de 90% o fator de potência é menos favorável).
limite_fp = 90
df2_critico = df2[(df2['Consumo_kWh'] > limiar2_75) & (df2['FP_Atraso'] < limite_fp)]
qtd2_critico = len(df2_critico)
print(f'Registros com consumo elevado e FP_Atraso < {limite_fp}: {qtd2_critico}')
print(f'Percentual da amostra: {qtd2_critico / len(df2) * 100:.2f}%')
df2_critico.head()

Registros com consumo elevado e FP_Atraso < 90: 42
Percentual da amostra: 0.60%


,Consumo_kWh,Pot_Reativa_Atraso_kVarh,Pot_Reativa_Avanco_kVarh,FP_Atraso,FP_Avanco,WeekStatus,Day_of_week,Load_Type
2,120.42,59.65,0.0,89.61,100.0,Weekday,Friday,Maximum_Load
295,129.85,63.86,0.0,89.74,100.0,Weekday,Friday,Maximum_Load
399,122.94,69.26,0.0,87.13,100.0,Weekday,Tuesday,Maximum_Load
605,134.60,66.24,0.0,89.72,100.0,Weekday,Monday,Maximum_Load
771,132.30,70.06,0.0,88.37,100.0,Weekend,Saturday,Medium_Load


Análise: o limiar de 75% do consumo máximo (114,85 kWh) seleciona 129 registros (1,84%), sendo 62 da categoria Maximum_Load, quase metade. Pelo describe() do FP_Atraso, a mediana fica perto de 100, então 90 foi adotado como limite para fator de potência baixo. O cruzamento resultou em 42 registros com consumo alto e FP_Atraso abaixo de 90. Esses períodos merecem mais atenção porque o fator de potência baixo aumenta a circulação de potência reativa justamente quando a carga já está alta, elevando as perdas e podendo gerar cobrança de excedente de reativos. São os principais candidatos a correção, por exemplo com banco de capacitores.

# Dataset 3: Power Consumption of Tetouan City (UCI)

Situação: uma equipe responsável pelo planejamento da distribuição de energia em Tétouan deseja identificar qual das três zonas apresenta o maior pico de consumo e observar as condições ambientais registradas nos momentos de maior demanda.

Amostra: 15% dos registros (tetouan_SAMPLE.csv), com as três zonas de consumo, Temperature, Humidity e Wind Speed.

In [27]:
# 1.	Carregar a amostra e renomear as três variáveis de consumo.
df3 = pd.read_csv('tetouan_SAMPLE.csv')
df3.rename(columns={'Zone 1 Power Consumption': 'Consumo_Zona_1',
                    'Zone 2  Power Consumption': 'Consumo_Zona_2',
                    'Zone 3  Power Consumption': 'Consumo_Zona_3'}, inplace=True)
df3.columns

Index(['Temperature', 'Humidity', 'Wind Speed', 'Consumo_Zona_1',
       'Consumo_Zona_2', 'Consumo_Zona_3'],
      dtype='object')

In [28]:
df3.head()

,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
0,22.76,29.73,0.085,32985.14532,19396.74134,17623.27273
1,15.92,54.44,0.085,34737.64259,29803.00706,14417.28691
2,15.08,57.23,0.076,27894.68354,20808.51064,16458.79518
3,12.42,72.30,0.081,42476.93617,23634.14634,25089.67742
4,14.58,80.60,0.080,21341.14101,12006.10998,11531.63636


In [29]:
print(f'Total de registros: {df3.shape[0]}')
print(f'Total de colunas: {df3.shape[1]}')

Total de registros: 7862
Total de colunas: 6


In [30]:
# 2.	Determine o consumo máximo registrado em cada uma das três zonas.
zonas = ['Consumo_Zona_1', 'Consumo_Zona_2', 'Consumo_Zona_3']
maximos3 = df3[zonas].max()
print(maximos3)

Consumo_Zona_1    51571.49834
Consumo_Zona_2    36437.17001
Consumo_Zona_3    47441.67364
dtype: float64


In [31]:
# 3.	Identifique qual zona apresenta o maior pico de consumo na amostra.
zona_pico = maximos3.idxmax()
print(f'Zona com o maior pico de consumo: {zona_pico} ({maximos3.max():.2f})')

Zona com o maior pico de consumo: Consumo_Zona_1 (51571.50)


In [32]:
# 4.	Para a zona identificada, calcule 70% do valor máximo e crie um DataFrame
#   	com os registros acima desse limiar.
limiar3_70 = 0.70 * maximos3.max()
print(f'Limiar (70% do máximo da {zona_pico}): {limiar3_70:.2f}')
df3_alto = df3[df3[zona_pico] > limiar3_70]
df3_alto.head()

Limiar (70% do máximo da Consumo_Zona_1): 36100.05


,Temperature,Humidity,Wind Speed,Consumo_Zona_1,Consumo_Zona_2,Consumo_Zona_3
3,12.42,72.30,0.081,42476.93617,23634.14634,25089.67742
8,14.66,65.92,0.075,37286.69202,30716.17060,15834.81393
12,21.03,86.50,0.068,40993.90728,25383.36798,24960.00000
14,27.06,47.58,4.905,37475.16093,24276.24076,25140.56426
19,19.20,65.81,4.924,40676.02649,24754.67775,25095.87692


In [33]:
# 5.	Conte os registros e calcule o percentual que eles representam.
qtd3_alto = len(df3_alto)
pct3_alto = qtd3_alto / len(df3) * 100
print(f'Registros acima do limiar: {qtd3_alto}')
print(f'Percentual da amostra: {pct3_alto:.2f}%')

Registros acima do limiar: 2388
Percentual da amostra: 30.37%


In [34]:
# 6.	Calcule a temperatura média e crie um segundo DataFrame com consumo acima do
#   	limiar e temperatura acima da média.
media3_temp = df3['Temperature'].mean()
print(f'Temperatura média da amostra: {media3_temp:.2f} °C')
df3_alto_temp = df3[(df3[zona_pico] > limiar3_70) & (df3['Temperature'] > media3_temp)]
qtd3_alto_temp = len(df3_alto_temp)
print(f'Registros com consumo alto e temperatura acima da média: {qtd3_alto_temp}')
print(f'Percentual da amostra: {qtd3_alto_temp / len(df3) * 100:.2f}%')

Temperatura média da amostra: 18.79 °C
Registros com consumo alto e temperatura acima da média: 1596
Percentual da amostra: 20.30%


In [35]:
# 7.	Compare os dois conjuntos.
print(f'Somente consumo > 70% do máximo: {qtd3_alto} registros')
print(f'Consumo alto e temperatura acima da média: {qtd3_alto_temp} registros')
print(f'Diferença: {qtd3_alto - qtd3_alto_temp} registros')

Somente consumo > 70% do máximo: 2388 registros
Consumo alto e temperatura acima da média: 1596 registros
Diferença: 792 registros


Análise: a Zona 1 tem o maior pico da amostra (51.571,50). Acima de 70% desse pico há 2.388 registros (30,37%), bem mais que nos outros datasets, porque a curva de carga de uma cidade é mais estável que a de uma residência ou indústria. Com a condição extra de temperatura acima da média (18,79 °C), o conjunto cai para 1.596 registros (20,30%). Cerca de dois terços dos momentos de alta demanda ocorrem com temperatura acima da média, o que é coerente com o peso da refrigeração no consumo urbano e ajuda a planejar a distribuição nos períodos quentes.

# Dataset 4: Solar Power Generation Data (Kaggle)

Situação: uma equipe de operação de uma usina fotovoltaica deseja localizar períodos de alta geração e identificar quais inversores aparecem com maior frequência nesses momentos. O foco é o arquivo de geração da Planta 1, sem junção com o arquivo de sensores.

Amostra: 20% dos registros (solar_plant1_SAMPLE.csv), com DATE_TIME, SOURCE_KEY, DC_POWER, AC_POWER, DAILY_YIELD e TOTAL_YIELD.

In [36]:
# 1.	Carregue a amostra e renomeie as principais variáveis para nomes mais claros.
df4 = pd.read_csv('solar_plant1_SAMPLE.csv')
df4.rename(columns={'DC_POWER': 'Potencia_CC',
                    'AC_POWER': 'Potencia_CA',
                    'DAILY_YIELD': 'Geracao_Diaria',
                    'TOTAL_YIELD': 'Geracao_Total'}, inplace=True)
df4.columns

Index(['DATE_TIME', 'SOURCE_KEY', 'Potencia_CC', 'Potencia_CA',
       'Geracao_Diaria', 'Geracao_Total'],
      dtype='object')

In [37]:
# 2.	Inspeção inicial
df4.head()

,DATE_TIME,SOURCE_KEY,Potencia_CC,Potencia_CA,Geracao_Diaria,Geracao_Total
0,10-06-2020 19:00,uHbuxQJl8lW7ozc,0.000,0.0000,6645.000,7240508.000
1,28-05-2020 00:15,rGa61gmuvPhdLxV,0.000,0.0000,0.000,7206549.000
2,17-05-2020 15:15,sjndEbLyjtCKgGv,7333.875,718.0625,6442.000,7036055.000
3,01-06-2020 04:15,ih0vzX44oOqAx2f,0.000,0.0000,0.000,6308232.000
4,17-05-2020 09:00,z9Y9gH1T5YWrNuG,7665.500,750.4375,961.375,7021701.375


In [38]:
print(f'Total de registros: {df4.shape[0]}')
print(f'Total de colunas: {df4.shape[1]}')

Total de registros: 13756
Total de colunas: 6


In [39]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13756 entries, 0 to 13755
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   DATE_TIME       13756 non-null  object 
 1   SOURCE_KEY      13756 non-null  object 
 2   Potencia_CC     13756 non-null  float64
 3   Potencia_CA     13756 non-null  float64
 4   Geracao_Diaria  13756 non-null  float64
 5   Geracao_Total   13756 non-null  float64
dtypes: float64(4), object(2)
memory usage: 644.9+ KB


In [40]:
df4.describe()

,Potencia_CC,Potencia_CA,Geracao_Diaria,Geracao_Total
count,13756.000000,13756.000000,13756.000000,1.375600e+04
mean,3135.848747,306.695495,3319.235219,6.978829e+06
std,4023.069798,393.124281,3142.249934,4.162164e+05
min,0.000000,0.000000,0.000000,6.183645e+06
25%,0.000000,0.000000,0.000000,6.509779e+06
50%,370.071429,35.771429,2730.428571,7.146218e+06
75%,6350.558036,622.065625,6293.785714,7.267996e+06
max,14416.142860,1405.585714,9163.000000,7.846821e+06


In [41]:
# 3.	Determine a maior potência CA registrada.
maximo4 = df4['Potencia_CA'].max()
print(f'Maior potência CA registrada: {maximo4} kW')

Maior potência CA registrada: 1405.585714 kW


In [42]:
# 4.	Calcule um limiar correspondente a 70% da potência CA máxima.
limiar4_70 = 0.70 * maximo4
print(f'Limiar (70% do máximo): {limiar4_70:.2f} kW')

Limiar (70% do máximo): 983.91 kW


In [43]:
# 5.	Crie um DataFrame somente com registros acima desse limite; quantidade e percentual.
df4_alto = df4[df4['Potencia_CA'] > limiar4_70]
qtd4_alto = len(df4_alto)
pct4_alto = qtd4_alto / len(df4) * 100
print(f'Registros de alta geração: {qtd4_alto}')
print(f'Percentual da amostra: {pct4_alto:.2f}%')
df4_alto.head()

Registros de alta geração: 1185
Percentual da amostra: 8.61%


,DATE_TIME,SOURCE_KEY,Potencia_CC,Potencia_CA,Geracao_Diaria,Geracao_Total
11,26-05-2020 12:15,bvBOhCH3iADSZry,11830.14286,1153.828571,4028.142857,6396364.143
46,15-06-2020 14:30,wCURE6d3bPkepu2,10571.28571,1032.071429,5366.571429,7015064.571
48,25-05-2020 10:15,z9Y9gH1T5YWrNuG,11050.14286,1079.857143,2174.285714,7082812.286
72,13-06-2020 11:30,7JYdWkrLSPkdwr4,11094.50000,1082.437500,3570.250000,7815987.250
76,07-06-2020 13:00,VHMLBKoKgIrUVDU,12663.42857,1234.685714,4976.714286,7382965.714


In [44]:
# 6.	Utilize value_counts() em SOURCE_KEY dentro do DataFrame de alta geração.
df4_alto['SOURCE_KEY'].value_counts()

SOURCE_KEY
adLQvlD726eNBSB    68
McdE0feGgRqW7Ca    65
ZnxXDlPa8U1GXgE    63
pkci93gMrogZuBj    62
ZoEaEvLYb1n2sOq    61
1IF53ai7Xc0U56Y    59
YxYtjZvoooNbGkE    58
sjndEbLyjtCKgGv    57
z9Y9gH1T5YWrNuG    56
uHbuxQJl8lW7ozc    55
zVJPv84UY57bAof    54
zBIq5rxdHJRwDNY    53
ih0vzX44oOqAx2f    53
WRmjgnKYAwPKWDb    52
3PZuoBAID5Wc2HD    51
VHMLBKoKgIrUVDU    51
iCRJl6heRkivqQ3    51
wCURE6d3bPkepu2    49
rGa61gmuvPhdLxV    43
7JYdWkrLSPkdwr4    43
1BY6WEcLGh8j5v7    42
bvBOhCH3iADSZry    39
Name: count, dtype: int64

In [45]:
# 7.	Identifique qual inversor aparece com maior frequência nos registros de alta geração.
inversor_top = df4_alto['SOURCE_KEY'].value_counts().idxmax()
freq_top = df4_alto['SOURCE_KEY'].value_counts().max()
print(f'Inversor mais frequente na alta geração: {inversor_top} ({freq_top} registros)')

Inversor mais frequente na alta geração: adLQvlD726eNBSB (68 registros)


Análise: há 1.185 registros de alta geração (8,61% da amostra). O inversor adLQvlD726eNBSB é o mais frequente (68 registros), mas os 22 inversores aparecem com frequências próximas (de 39 a 68). Isso indica que a alta geração depende da irradiância na planta como um todo, e esse recorte sozinho não permite concluir desempenho melhor nem falha de nenhum inversor. Para isso seria preciso analisar mais dados, como os sensores e os períodos de indisponibilidade.

# Dataset 5: Wind & Solar Energy Production (Kaggle)

Situação: um operador de um portfólio de fontes renováveis deseja comparar a ocorrência de períodos de alta produção solar e alta produção eólica. Como as duas fontes possuem escalas próprias, cada uma deve ser comparada com o seu próprio valor máximo.

Amostra: 20% dos registros (windsolar_SAMPLE.csv), com a produção horária solar e eólica em MW reorganizada em duas colunas a partir do atributo Source.

In [46]:
# 1.	Renomeie as variáveis principais para Geracao_Solar e Geracao_Eolica.
df5 = pd.read_csv('windsolar_SAMPLE.csv')
df5.rename(columns={'Solar': 'Geracao_Solar', 'Wind': 'Geracao_Eolica'}, inplace=True)
df5.head()

,Date and Hour,Geracao_Solar,Geracao_Eolica
0,2021-09-05 10:00:00+02:00,3269.0,92.0
1,2022-02-23 21:00:00+01:00,2.0,2265.0
2,2023-01-05 01:00:00+01:00,1.0,11490.0
3,2020-11-29 07:00:00+01:00,0.0,4430.0
4,2020-09-07 04:00:00+02:00,0.0,1606.0


In [47]:
print(f'Total de registros: {df5.shape[0]}')
df5.describe()

Total de registros: 5980


,Geracao_Solar,Geracao_Eolica
count,5980.000000,5980.000000
mean,1054.760033,4494.437291
std,1545.080990,3503.181279
min,0.000000,44.000000
25%,1.000000,1819.000000
50%,28.000000,3379.000000
75%,1900.500000,6291.500000
max,7489.000000,17168.000000


In [48]:
# 2.	Determine o valor máximo registrado para cada fonte.
max_solar = df5['Geracao_Solar'].max()
max_eolica = df5['Geracao_Eolica'].max()
print(f'Máximo solar:  {max_solar} MW')
print(f'Máximo eólico: {max_eolica} MW')

Máximo solar:  7489.0 MW
Máximo eólico: 17168.0 MW


In [49]:
# 3.	Calcule separadamente 70% do máximo solar e 70% do máximo eólico.
limiar_solar = 0.70 * max_solar
limiar_eolica = 0.70 * max_eolica
print(f'Limiar solar (70% do máximo solar):   {limiar_solar:.2f} MW')
print(f'Limiar eólico (70% do máximo eólico): {limiar_eolica:.2f} MW')

Limiar solar (70% do máximo solar):   5242.30 MW
Limiar eólico (70% do máximo eólico): 12017.60 MW


In [50]:
# 4.	Crie um DataFrame para alta geração solar e outro para alta geração eólica.
df5_alta_solar = df5[df5['Geracao_Solar'] > limiar_solar]
df5_alta_eolica = df5[df5['Geracao_Eolica'] > limiar_eolica]
print(f'Registros de alta geração solar:  {len(df5_alta_solar)}')
print(f'Registros de alta geração eólica: {len(df5_alta_eolica)}')

Registros de alta geração solar:  124
Registros de alta geração eólica: 296


In [51]:
# 5.	Conte os registros de cada DataFrame e calcule seus respectivos percentuais.
pct_solar = len(df5_alta_solar) / len(df5) * 100
pct_eolica = len(df5_alta_eolica) / len(df5) * 100
print(f'Alta geração solar:  {len(df5_alta_solar)} registros ({pct_solar:.2f}% da amostra)')
print(f'Alta geração eólica: {len(df5_alta_eolica)} registros ({pct_eolica:.2f}% da amostra)')

Alta geração solar:  124 registros (2.07% da amostra)
Alta geração eólica: 296 registros (4.95% da amostra)


In [52]:
# 6.	Compare qual fonte aparece com maior frequência acima de 70% do seu próprio máximo.
fonte = 'eólica' if len(df5_alta_eolica) > len(df5_alta_solar) else 'solar'
print(f'A fonte {fonte} aparece com maior frequência acima de 70% do seu próprio máximo.')

A fonte eólica aparece com maior frequência acima de 70% do seu próprio máximo.


Análise: comparando cada fonte com o próprio máximo, a eólica fica acima de 70% do seu máximo com mais frequência (296 registros, 4,95%) do que a solar (124 registros, 2,07%). Faz sentido, porque a solar só gera durante o dia e concentra os valores altos perto do meio-dia, enquanto a eólica pode operar perto da capacidade em qualquer horário. Não daria para usar o mesmo valor numérico como limite para as duas fontes: o máximo solar é 7.489 MW e o eólico 17.168 MW, então um limite de 12.018 MW nunca seria atingido pela solar. Por isso o limiar precisa ser relativo ao máximo de cada fonte.

# Dataset 6: Individual Household Electric Power Consumption (UCI)

Situação: uma residência possui monitoramento elétrico detalhado e deseja identificar episódios de demanda elevada que também apresentem corrente acima do comportamento médio.

Amostra: 10% do dataset completo (household_SAMPLE.csv), gerada após a remoção das linhas com valores ausentes e a seleção de Global_active_power, Global_reactive_power, Voltage, Global_intensity e os três Sub_metering.

In [53]:
# 1.	Carregue a nova amostra e organize os atributos utilizando nomes mais simples.
df6 = pd.read_csv('household_SAMPLE.csv')
df6.rename(columns={'Global_active_power': 'Potencia_Ativa',
                    'Global_reactive_power': 'Potencia_Reativa',
                    'Voltage': 'Tensao',
                    'Global_intensity': 'Corrente',
                    'Sub_metering_1': 'Sub_Medicao_1',
                    'Sub_metering_2': 'Sub_Medicao_2',
                    'Sub_metering_3': 'Sub_Medicao_3'}, inplace=True)
df6.head()

,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Sub_Medicao_1,Sub_Medicao_2,Sub_Medicao_3
0,1.502,0.074,240.17,6.4,0.0,0.0,18.0
1,0.374,0.264,245.50,1.8,0.0,2.0,0.0
2,0.620,0.300,239.85,3.0,0.0,1.0,1.0
3,0.280,0.200,235.72,1.4,0.0,0.0,0.0
4,1.372,0.054,243.95,5.6,0.0,0.0,18.0


In [54]:
print(f'Total de registros: {df6.shape[0]}')
df6.info()

Total de registros: 204928
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204928 entries, 0 to 204927
Data columns (total 7 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Potencia_Ativa    204928 non-null  float64
 1   Potencia_Reativa  204928 non-null  float64
 2   Tensao            204928 non-null  float64
 3   Corrente          204928 non-null  float64
 4   Sub_Medicao_1     204928 non-null  float64
 5   Sub_Medicao_2     204928 non-null  float64
 6   Sub_Medicao_3     204928 non-null  float64
dtypes: float64(7)
memory usage: 10.9 MB


In [55]:
# 2.	Determine o valor máximo de potência ativa.
maximo6 = df6['Potencia_Ativa'].max()
print(f'Potência ativa máxima: {maximo6} kW')

Potência ativa máxima: 10.536 kW


In [56]:
# 3.	Calcule 75% do valor máximo e crie um DataFrame com registros acima desse limite.
limiar6_75 = 0.75 * maximo6
print(f'Limiar (75% do máximo): {limiar6_75:.3f} kW')
df6_alto = df6[df6['Potencia_Ativa'] > limiar6_75]
df6_alto.head()

Limiar (75% do máximo): 7.902 kW


,Potencia_Ativa,Potencia_Reativa,Tensao,Corrente,Sub_Medicao_1,Sub_Medicao_2,Sub_Medicao_3
3132,8.540,0.238,236.23,36.0,80.0,35.0,17.0
3630,8.278,0.088,231.50,35.6,0.0,71.0,17.0
10339,8.026,0.066,236.45,33.8,37.0,73.0,18.0
11695,8.102,0.190,229.31,35.4,35.0,35.0,17.0
27983,10.290,0.302,230.90,44.6,35.0,66.0,17.0


In [57]:
# 4.	Calcule a quantidade e o percentual de registros selecionados.
qtd6_alto = len(df6_alto)
pct6_alto = qtd6_alto / len(df6) * 100
print(f'Registros acima do limiar: {qtd6_alto}')
print(f'Percentual da amostra: {pct6_alto:.3f}%')

Registros acima do limiar: 58
Percentual da amostra: 0.028%


In [58]:
# 5.	Calcule a corrente média da amostra.
media6_corrente = df6['Corrente'].mean()
print(f'Corrente média da amostra: {media6_corrente:.2f} A')

Corrente média da amostra: 4.63 A


In [59]:
# 6.	Segundo DataFrame: potência ativa acima de 75% do máximo E corrente acima da média.
df6_alto_corr = df6[(df6['Potencia_Ativa'] > limiar6_75) & (df6['Corrente'] > media6_corrente)]
qtd6_alto_corr = len(df6_alto_corr)
print(f'Registros com potência alta e corrente acima da média: {qtd6_alto_corr}')
print(f'Percentual da amostra: {qtd6_alto_corr / len(df6) * 100:.3f}%')

Registros com potência alta e corrente acima da média: 58
Percentual da amostra: 0.028%


In [60]:
# 7.	Compare os dois conjuntos.
print(f'Somente potência > 75% do máximo: {qtd6_alto} registros')
print(f'Potência alta e corrente acima da média: {qtd6_alto_corr} registros')
print(f'Diferença: {qtd6_alto - qtd6_alto_corr} registros')

Somente potência > 75% do máximo: 58 registros
Potência alta e corrente acima da média: 58 registros
Diferença: 0 registros


Análise: acima de 75% do máximo de potência ativa (7,902 kW) há 58 registros (0,028% da amostra). Ao exigir também corrente acima da média (4,63 A), permanecem os mesmos 58, ou seja, a segunda condição não eliminou nenhum caso. Isso acontece porque a potência ativa é aproximadamente o produto da tensão pela corrente e a tensão varia pouco (perto de 240 V): manter mais de 7,9 kW exige uns 33 A, muito acima da média. Nesse limiar a condição de corrente é redundante e só filtraria algo com um limiar de potência mais baixo. Ao combinar condições com & vale checar se uma já implica a outra.